- hosts: kafka-boxes
  user: hduser
  sudo: no
  vars:
    confluent_version: 2.0.0-2.11.7
    package_name: confluent-2.0.0-2.11.7
    abbrev_package_name: confluent-2.0.0
    install_path: /usr/local/{{abbrev_package_name}}
    template_path: ../../templates/kafka
  tasks:
    - shell: "{{install_path}}/bin/kafka-server-start -daemon {{install_path}}/etc/kafka.properties"
      args:
        executable: /bin/bash

