---
- name: install tmux prefs
  get_url:
    url: https://gist.githubusercontent.com/brycemcd/c43f5a3250256cd65686/raw/.tmux.conf
    dest: ~/.tmux.conf
    mode: 0744

- authorized_key:
    user: brycemcd
    key: https://github.com/brycemcd.keys

