---
- hosts: new-elastic-boxes
  user: brycemcd
  sudo: yes
  vars:
    #elasticsearch_env_filename: spark_environment_params
    local_elasticsearch_template_path: ../../templates/elasticsearch
    env_vars_path: /home/hduser/.es_env_vars
    es_data_path: /usr/local/elasticsearch-1.7.3/data
  tasks:
    # https://www.elastic.co/downloads/past-releases/elasticsearch-1-7-3
    - name: remove existing download if exists
      command: rm -rf elasticsearch-1.7.3.deb
      ignore_errors: True

    - name: download es
      command: wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.3.deb

    - apt: deb=elasticsearch-1.7.3.deb

    - lineinfile: dest=/home/hduser/.bashrc line="export ~/.es_env_vars" state=absent


    - template: src={{local_elasticsearch_template_path}}/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml mode=0755

    - name: create data path
      file: path={{es_data_path}} state=directory mode=0755 owner=elasticsearch group=elasticsearch recurse=yes
