---
- hosts: hadoop-master
  user: hduser
  sudo: no
  tasks:
    - name: stop dfs
      shell: "{{hadoop_install_path}}/sbin/stop-dfs.sh"
      args:
        executable: /bin/bash

    - name: stop yarn
      shell: "{{hadoop_install_path}}/sbin/stop-yarn.sh"
      args:
        executable: /bin/bash
