---
- hosts: new-hadoop-boxes
  user: brycemcd
  sudo: yes
  tasks:
    - name: Adds hduser
      user: name=hduser comment="Hadoop Apps should run under this user"
    - group: name=hadoop state=present
    - authorized_key: user=hduser key=https://github.com/brycemcd.keys

    # FIXME: this was originally intended to be hadoop only
    #- name: copy hadoop env_vars into bash.rc include
      #template: src=../templates/hadoop/hadoop_env_vars dest=/home/brycemcd/.hadoop_env_vars mode=0644 owner=brycemcd

    #- name: update .bashrc
      #shell: echo "source ~/.hadoop_env_vars" >> /home/brycemcd/.bashrc
      #args:
        #executable: /bin/bash

    #- name: source new .bashrc
      #sudo: no
      #shell: source /home/brycemcd/.bashrc
      #args:
        #executable: /bin/bash

- hosts: new-hadoop-boxes
  user: hduser
  sudo: no
  tasks:
    - name: copy hadoop env_vars into bash.rc include
      template: src=../templates/hadoop/hadoop_env_vars dest=/home/hduser/.hadoop_env_vars mode=0644 owner=hduser

    # TODO ZSH!!!
    - name: update .bashrc
      shell: echo "source ~/.hadoop_env_vars" >> /home/hduser/.bashrc
      args:
        executable: /bin/bash

    - name: source new .bashrc
      sudo: no
      shell: source /home/hduser/.bashrc
      args:
        executable: /bin/bash
