---
# NOTE: this was helpful. I'm not sure the code in this playbook works.
# https://linuxconfig.org/how-to-install-kubernetes-on-ubuntu-18-04-bionic-beaver-linux
- hosts: kube-slave-nodes
  become: yes
  become_method: sudo
  tasks:
  - include_tasks: ../common_tasks/install_docker.yml
  - apt:
       name: "{{item}}"
       state: latest
       update_cache: yes
       install_recommends: yes
    with_items:
      - apt-transport-https
      - curl

  - apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  # NOTE: I should use an apt-* module but I couldn't get it to work right
  - name: add kube repository
    command: apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

  # NOTE: until I reconfigure the memory/storage on these boxes, this will
  # have to do. It's going to cause problems. Manually go in and edit /etc/fstab
  # in order to prevent swap from re-mounting on reboot.
  - command: "swapoff -a"

  - apt:
       name: "{{item}}"
       state: latest
       update_cache: yes
       install_recommends: yes
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - command: systemctl daemon-reload
  - command: systemctl restart kubelet

  # NOTE: This is a manual step that needs to take place at the end. I haven't
  # figured out how to automate this yet.
  #  kubeadm join 10.1.2.216:6443 --token [token-value] --discovery-token-ca-cert-hash sha256:[a-hash]
