---
- hosts: kafka-boxes
  user: brycemcd
  sudo: yes
  vars:
    confluent_version: 2.0.0-2.11.7
    package_name: confluent-2.0.0-2.11.7
    abbrev_package_name: confluent-2.0.0
    install_path: /usr/local/{{abbrev_package_name}}
    template_path: ../../templates/kafka
  tasks:

#    - command: rm {{package_name}}.tar.gz
#      ignore_errors: True

#    - name: download kafka
#      command: wget http://packages.confluent.io/archive/2.0/{{package_name}}.tar.gz

    - command: rm -rf {{package_name}}
      ignore_errors: True

    - command: tar zxvf {{package_name}}.tar.gz

    - command: rm -rf {{install_path}}
      ignore_errors: True

    - command: mv {{abbrev_package_name}} /usr/local/

    - file: dest={{install_path}}/logs state=directory mode=0755 owner=hduser group=hadoop
        recurse=yes

    - template: dest={{install_path}}/etc/kafka.properties src={{template_path}}/server.properties
        mode=0755
