---
- hosts: hadoop-master
  user: hduser
  sudo: no
  tasks:
    - name: fire up dfs
      shell: "{{hadoop_install_path}}/sbin/start-dfs.sh"
      args:
        executable: /bin/bash

    - name: fire up the yarn
      shell: "{{hadoop_install_path}}/sbin/start-yarn.sh"
      args:
        executable: /bin/bash
