---
- hosts: kafka
  become: yes
  become_method: sudo
  vars:
    zookeeper_seed_master: 10.1.2.244
  tasks:
    - name: docker-compose down kafka and zookeeper
      command: docker-compose down
      args:
        chdir: /opt/kafka
